FROM golang:1.25-alpine AS builder

RUN apk update && apk add --no-cache git curl

RUN go install github.com/air-verse/air@v1.63.0

WORKDIR /app

COPY . .

CMD ["air", "-c", ".air.worker.toml"]